"""Registration data for the prototype connectors. `build(Source)` returns {name: Source} for the
whole prototype library; `plugins.py` looks up the names listed in the global config's
`plugins.prototypes` and appends those Sources to the live registry. Kept separate from
`bean/sources.py` (and taking `Source` as an argument) so importing a prototype never pulls the
core registry back in — no import cycle.

To promote a prototype to a real connector, move its module up into `bean/` and add a row to
`CORE_SOURCES` in `sources.py`; to ship your own, drop a module exposing `SOURCE` into
~/.bean/plugins/ (see the `bean-connector` skill)."""

from __future__ import annotations

from . import (airtable, asana, axero, bitbucket, bookstack, braintrust, buckets, canvas, clickup,
               coda, discourse, document360, dropbox, drupal_wiki, egnyte, figma, fireflies,
               freshdesk, gitbook, gitlab, gmail, gong, google_site, gsheets, guru, highspot, imap,
               intercom, linear, loopio, mediawiki, obsidian, outline, productboard, readwise, rss,
               servicenow, slab, sqldb, testrail, trello, web, wikipedia, xenforo, zulip)


def build(Source) -> dict:
    """name -> Source for every prototype. `Source` is passed in to avoid importing sources.py."""
    rows = [
        # -- Google (ride gcloud) ---------------------------------------------------------------
        Source("gsheets", "gsheets", "Google Sheets", ("sheets",), gsheets.sync, gsheets.parse_add,
               auth="google", add_help="gsheet:ID or a docs.google.com/spreadsheets/d/ID URL",
               auth_help="rides `bean auth google` (gcloud)",
               connect=gsheets.connect, connected=gsheets.connected, interactive_auth=True),
        Source("gmail", "gmail", "Gmail", ("queries", "labels"), gmail.sync, gmail.parse_add,
               auth="gmail", add_help="gmail:label:INBOX or gmail:<search query>",
               auth_help="(gcloud: reuses `bean auth google`) or --email … --token <app-password> for IMAP",
               connect=gmail.connect, connected=gmail.connected, interactive_auth=True),
        # -- issue / project trackers -----------------------------------------------------------
        Source("linear", "linear", "Linear", ("teams",), linear.sync, linear.parse_add, auth="linear",
               add_help="linear:TEAMKEY or a linear.app issue/team URL", auth_help="--token <api-key>",
               connect=linear.connect, connected=linear.connected),
        Source("asana", "asana", "Asana", ("projects",), asana.sync, asana.parse_add, auth="asana",
               add_help="asana:PROJECT_GID or an app.asana.com project URL", auth_help="--token <pat>",
               connect=asana.connect, connected=asana.connected),
        Source("trello", "trello", "Trello", ("boards",), trello.sync, trello.parse_add, auth="trello",
               add_help="trello:BOARDID or a trello.com/b/… board URL",
               auth_help="--key <api-key> --token <token>",
               connect=trello.connect, connected=trello.connected),
        Source("gitlab", "gitlab", "GitLab", ("projects",), gitlab.sync, gitlab.parse_add,
               auth="gitlab", add_help="gitlab:group/project or a gitlab.com project URL",
               auth_help="--token <pat> [--url https://self-managed]",
               connect=gitlab.connect, connected=gitlab.connected),
        Source("bitbucket", "bitbucket", "Bitbucket", ("repos",), bitbucket.sync, bitbucket.parse_add,
               auth="bitbucket", add_help="bitbucket:workspace/repo or a bitbucket.org repo URL",
               auth_help="--email <atlassian-email> --secret <app-password>",
               connect=bitbucket.connect, connected=bitbucket.connected),
        Source("clickup", "clickup", "ClickUp", ("lists", "spaces", "tasks"), clickup.sync,
               clickup.parse_add, auth="clickup",
               add_help="clickup:list:ID, clickup:space:ID, clickup:task:ID, or an app.clickup.com/t/… URL",
               auth_help="--token pk_…", connect=clickup.connect, connected=clickup.connected),
        Source("productboard", "productboard", "Productboard", ("include",), productboard.sync,
               productboard.parse_add, auth="productboard",
               add_help="productboard:notes or productboard:features (optional; both sync by default)",
               auth_help="--token <access-token>",
               connect=productboard.connect, connected=productboard.connected, always_when_connected=True),
        Source("testrail", "testrail", "TestRail", ("projects",), testrail.sync, testrail.parse_add,
               auth="testrail", add_help="testrail:project:ID",
               auth_help="--url https://you.testrail.io --email … --token <api-key>",
               connect=testrail.connect, connected=testrail.connected),
        Source("canvas", "canvas", "Canvas", ("courses",), canvas.sync, canvas.parse_add,
               auth="canvas", add_help="canvas:course:ID or an instructure.com/courses/ID URL",
               auth_help="--url https://school.instructure.com --token <access-token>",
               connect=canvas.connect, connected=canvas.connected),
        # -- wikis / knowledge bases ------------------------------------------------------------
        Source("coda", "coda", "Coda", ("docs",), coda.sync, coda.parse_add, auth="coda",
               add_help="a Coda doc id (coda:DOCID) or a coda.io/d/… URL", auth_help="--token <api-token>",
               connect=coda.connect, connected=coda.connected),
        Source("servicenow", "servicenow", "ServiceNow", ("tables",), servicenow.sync,
               servicenow.parse_add, auth="servicenow",
               add_help="servicenow:kb_knowledge or servicenow:incident (optional; both sync by default)",
               auth_help="--subdomain instance (--email … --secret <password> | --token <bearer>)",
               connect=servicenow.connect, connected=servicenow.connected, always_when_connected=True),
        Source("guru", "guru", "Guru", ("collections",), guru.sync, guru.parse_add, auth="guru",
               add_help="guru:<collection> to restrict (optional; all cards sync by default)",
               auth_help="--email <guru user> --token <user token>",
               connect=guru.connect, connected=guru.connected, always_when_connected=True),
        Source("gitbook", "gitbook", "GitBook", ("spaces",), gitbook.sync, gitbook.parse_add,
               auth="gitbook", add_help="gitbook:SPACEID or a gitbook.com space URL",
               auth_help="--token <api token>", connect=gitbook.connect, connected=gitbook.connected),
        Source("outline", "outline", "Outline", ("collections",), outline.sync, outline.parse_add,
               auth="outline", add_help="outline:COLLECTIONID to restrict (optional; all docs by default)",
               auth_help="--url https://your.outline.host --token <api token>",
               connect=outline.connect, connected=outline.connected, always_when_connected=True),
        Source("slab", "slab", "Slab", ("tags",), slab.sync, slab.parse_add, auth="slab",
               add_help="slab:tag:<name> to restrict (optional; all posts sync by default)",
               auth_help="--token <api token>", connect=slab.connect, connected=slab.connected,
               always_when_connected=True),
        Source("bookstack", "bookstack", "BookStack", ("books",), bookstack.sync, bookstack.parse_add,
               auth="bookstack", add_help="bookstack:book:ID to restrict (optional; all pages by default)",
               auth_help="--url https://your.bookstack --key <token id> --secret <token secret>",
               connect=bookstack.connect, connected=bookstack.connected, always_when_connected=True),
        Source("document360", "document360", "Document360", ("categories",), document360.sync,
               document360.parse_add, auth="document360",
               add_help="document360:category:<name> to restrict (optional; all articles by default)",
               auth_help="--token <api token>",
               connect=document360.connect, connected=document360.connected, always_when_connected=True),
        Source("mediawiki", "mediawiki", "MediaWiki", ("categories", "pages"), mediawiki.sync,
               mediawiki.parse_add, auth="mediawiki",
               add_help="mediawiki:Category:Name or mediawiki:Page Title",
               auth_help="--url https://wiki.example.org/w/api.php  (public wikis need no token)",
               connect=mediawiki.connect, connected=mediawiki.connected),
        Source("wikipedia", "wikipedia", "Wikipedia", ("pages", "categories"), wikipedia.sync,
               wikipedia.parse_add, auth="wikipedia",
               add_help="wikipedia:Page Title, wikipedia:Category:Name, or an en.wikipedia.org/wiki/… URL",
               auth_help="--url en  (language edition, default en; no token)",
               connect=wikipedia.connect, connected=wikipedia.connected),
        Source("drupalwiki", "drupalwiki", "Drupal Wiki", ("spaces",), drupal_wiki.sync,
               drupal_wiki.parse_add, auth="drupalwiki",
               add_help="drupalwiki:SPACEID (optional; all spaces sync by default)",
               auth_help="--url https://your.drupal-wiki.com --token <bearer>",
               connect=drupal_wiki.connect, connected=drupal_wiki.connected, always_when_connected=True),
        Source("axero", "axero", "Axero", ("spaces",), axero.sync, axero.parse_add, auth="axero",
               add_help="axero:SPACEID (optional; whole deployment syncs by default)",
               auth_help="--url https://you.axerosolutions.com --key <rest-api-key>",
               connect=axero.connect, connected=axero.connected, always_when_connected=True),
        # -- support / CRM / forums / sales -----------------------------------------------------
        Source("intercom", "intercom", "Intercom", ("tags",), intercom.sync, intercom.parse_add,
               auth="intercom", add_help="intercom:tag:<name> to restrict (optional; all by default)",
               auth_help="--token <access-token>",
               connect=intercom.connect, connected=intercom.connected, always_when_connected=True),
        Source("freshdesk", "freshdesk", "Freshdesk", ("include",), freshdesk.sync, freshdesk.parse_add,
               auth="freshdesk", add_help="freshdesk:tickets or freshdesk:solutions",
               auth_help="--subdomain acme --key <api-key>",
               connect=freshdesk.connect, connected=freshdesk.connected, always_when_connected=True),
        Source("gong", "gong", "Gong", ("include",), gong.sync, gong.parse_add, auth="gong",
               add_help="gong:workspace:<id> to restrict (optional; all calls by default)",
               auth_help="--key <access-key> --secret <access-key-secret>",
               connect=gong.connect, connected=gong.connected, always_when_connected=True),
        Source("fireflies", "fireflies", "Fireflies", ("include",), fireflies.sync, fireflies.parse_add,
               auth="fireflies", add_help="fireflies:organizer:<email> to restrict (optional)",
               auth_help="--token <api-key>",
               connect=fireflies.connect, connected=fireflies.connected, always_when_connected=True),
        Source("highspot", "highspot", "Highspot", ("spots",), highspot.sync, highspot.parse_add,
               auth="highspot", add_help="highspot:spot:<name> to restrict (optional; all spots by default)",
               auth_help="--key <api-key> --secret <api-secret>",
               connect=highspot.connect, connected=highspot.connected, always_when_connected=True),
        Source("loopio", "loopio", "Loopio", ("include",), loopio.sync, loopio.parse_add, auth="loopio",
               add_help="loopio:stack:<name> to restrict (optional; whole Library by default)",
               auth_help="--key <client-id> --secret <client-secret> [--subdomain acme]",
               connect=loopio.connect, connected=loopio.connected, always_when_connected=True),
        Source("discourse", "discourse", "Discourse", ("categories",), discourse.sync,
               discourse.parse_add, auth="discourse",
               add_help="discourse:category:ID (optional; latest topics sync by default)",
               auth_help="--url https://forum.example.com [--token <api-key> --email <api-username>]",
               connect=discourse.connect, connected=discourse.connected, always_when_connected=True),
        Source("xenforo", "xenforo", "XenForo", ("forums", "threads"), xenforo.sync, xenforo.parse_add,
               auth="xenforo",
               add_help="xenforo:forum:ID, xenforo:thread:ID, or a /threads/… URL (optional; whole board)",
               auth_help="--url https://forum.example.com --key <XF-Api-Key>",
               connect=xenforo.connect, connected=xenforo.connected, always_when_connected=True),
        # -- personal / structured / files ------------------------------------------------------
        Source("readwise", "readwise", "Readwise", ("tags",), readwise.sync, readwise.parse_add,
               auth="readwise", add_help="readwise:highlights or readwise:reader (optional; both by default)",
               auth_help="--token <access-token>",
               connect=readwise.connect, connected=readwise.connected, always_when_connected=True),
        Source("figma", "figma", "Figma", ("files",), figma.sync, figma.parse_add, auth="figma",
               add_help="a Figma file key (figma:KEY) or a figma.com/file|design/KEY/… URL",
               auth_help="--token <personal-access-token>",
               connect=figma.connect, connected=figma.connected),
        Source("braintrust", "braintrust", "Braintrust", ("projects",), braintrust.sync,
               braintrust.parse_add, auth="braintrust", add_help="braintrust:PROJECT",
               auth_help="--token <api-key>", connect=braintrust.connect, connected=braintrust.connected,
               always_when_connected=True),
        Source("airtable", "airtable", "Airtable", ("tables",), airtable.sync, airtable.parse_add,
               auth="airtable", add_help="airtable:BASEID/TABLE or an airtable.com/BASE/TABLE URL",
               auth_help="--token pat… (airtable.com/create/tokens)",
               connect=airtable.connect, connected=airtable.connected),
        Source("dropbox", "dropbox", "Dropbox", ("folders",), dropbox.sync, dropbox.parse_add,
               auth="dropbox", add_help="dropbox:/Folder/Path",
               auth_help="--token sl.… (Dropbox App Console → generated access token)",
               connect=dropbox.connect, connected=dropbox.connected),
        Source("egnyte", "egnyte", "Egnyte", ("folders",), egnyte.sync, egnyte.parse_add, auth="egnyte",
               add_help="egnyte:/Shared/Path",
               auth_help="--subdomain <company> --token <access-token>",
               connect=egnyte.connect, connected=egnyte.connected),
        Source("buckets", "buckets", "Cloud Storage", ("buckets",), buckets.sync, buckets.parse_add,
               auth=None, add_help="s3://bucket/prefix, gs://bucket/prefix, az://account/container/prefix"),
        # -- chat / mail ------------------------------------------------------------------------
        Source("zulip", "zulip", "Zulip", ("streams",), zulip.sync, zulip.parse_add, auth="zulip",
               add_help="zulip:STREAM (optional; subscribed streams sync by default)",
               auth_help="--url https://you.zulipchat.com --email bot@you.zulipchat.com --token <api-key>",
               connect=zulip.connect, connected=zulip.connected),
        Source("imap", "imap", "IMAP mail", ("mailboxes",), imap.sync, imap.parse_add, auth="imap",
               add_help="imap:MAILBOX (optional; INBOX by default)",
               auth_help="--url imap.host[:port] --email you@host --secret <password-or-app-password>",
               connect=imap.connect, connected=imap.connected),
        # -- feeds / web / local ----------------------------------------------------------------
        Source("google_site", "google_site", "Google Sites", ("sites",), google_site.sync,
               google_site.parse_add, auth=None, add_help="gsite:https://sites.google.com/…"),
        Source("rss", "rss", "RSS/Atom", ("feeds",), rss.sync, rss.parse_add, auth=None,
               add_help="rss:URL or feed:URL"),
        Source("sqldb", "sqldb", "SQL database", ("queries",), sqldb.sync, sqldb.parse_add, auth=None,
               add_help="sql:{dsn}|{SELECT …}  (e.g. sql:sqlite:///data.db|SELECT id,title,body,url FROM t)"),
        Source("obsidian", "obsidian", "Obsidian vault", ("vaults",), obsidian.sync, obsidian.parse_add,
               auth=None, add_help="obsidian:/path/to/vault"),
        Source("web", "web", "Web pages", ("pages", "sitemaps"), web.sync, web.parse_add, auth=None,
               add_help="web:URL, sitemap:URL, or a plain http(s) URL"),
    ]
    return {s.key: s for s in rows}


def names() -> list[str]:
    """Every prototype key, cheap (no Source construction) for `bean plugins list`."""
    return sorted(m.split(".")[-1] for m in _KEYS)


_KEYS = (
    "gsheets", "gmail", "linear", "asana", "trello", "gitlab", "bitbucket", "clickup",
    "productboard", "testrail", "canvas", "coda", "servicenow", "guru", "gitbook", "outline",
    "slab", "bookstack", "document360", "mediawiki", "wikipedia", "drupalwiki", "axero", "intercom",
    "freshdesk", "gong", "fireflies", "highspot", "loopio", "discourse", "xenforo", "readwise",
    "figma", "braintrust", "airtable", "dropbox", "egnyte", "buckets", "zulip", "imap",
    "google_site", "rss", "sqldb", "obsidian", "web",
)
